In [4]:
import numpy as np
n1=np.array([1,2,3,4])
n1


array([1, 2, 3, 4])

In [5]:
import numpy as np
n2=np.array([[1,2,3,3],[2,3,4,5]])
n2

array([[1, 2, 3, 3],
       [2, 3, 4, 5]])

In [6]:
import numpy as np
n2=np.array([[1,2,3,3],[2,3,4,5]])

n2


array([[1, 2, 3, 3],
       [2, 3, 4, 5]])

In [7]:
type(n1)

numpy.ndarray

In [8]:
type(n2)

numpy.ndarray

In [9]:
n3=np.array([1,3,0,3,0])
n3

array([1, 3, 0, 3, 0])

In [10]:
type(n3)

numpy.ndarray

In [11]:
n4=np.zeros((9,2))

In [12]:
n4

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
hi=np.full((3,4),67)
hi

array([[67, 67, 67, 67],
       [67, 67, 67, 67],
       [67, 67, 67, 67]])

In [14]:
type(hi)

numpy.ndarray

In [15]:
n1=np.full((8,1),3)

In [16]:
n1

array([[3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3]])

In [17]:
n3=np.zeros((3,9))

In [18]:
n3


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
n1=np.zeros(0)

In [ ]:
n1=np.arange(8,99)

In [ ]:
n1

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
       76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
       93, 94, 95, 96, 97, 98])

In [ ]:
n4=np.zeros((9,2))

In [ ]:
n4


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
n4=np.zeros(9)

In [ ]:
n1=np.random.randint(8,90,89)

In [ ]:
n1

array([19,  9, 22, 23, 13, 27, 71, 65, 81, 62, 14, 69, 27, 31, 87, 58, 75,
       49, 14, 18, 30, 89, 21, 63, 24, 34, 78, 40, 41, 44, 77, 54, 39, 26,
       66, 78, 46, 17, 45, 43, 60, 12, 41, 46, 16, 61, 19, 14, 83, 19, 71,
       35, 53, 46, 10, 44, 84, 83, 20, 46, 73, 25, 19, 67, 52, 50, 32, 88,
       49,  9, 33,  8, 37, 10, 53,  8, 40, 63, 75, 16, 30, 21, 54, 34, 52,
       19, 82, 71, 25])

In [ ]:
n2=np.random.randint(1,5,10)

In [ ]:
n2

array([1, 1, 1, 3, 4, 2, 1, 3, 2, 1])

In [ ]:
n2=np.random.randint(1,5,10)
n2

array([3, 1, 1, 4, 1, 3, 4, 2, 4, 1])

In [23]:
#n2=np.random.randint(1,1,10)
#n2

In [24]:
#n2=np.array([1,2,3,4],[2,2,2,2])

In [ ]:
n2=np.array([[1,2,3,4],[2,2,2,2]])
n2

array([[1, 2, 3, 4],
       [2, 2, 2, 2]])

In [ ]:
n2.shape

(2, 4)

In [ ]:
n2.shape=(2,4)
n2

array([[1, 2, 3, 4],
       [2, 2, 2, 2]])

In [25]:
#n2.shape=(3,4)


In [ ]:
n2.shape=(8,1)

In [ ]:
n2

array([[1],
       [2],
       [3],
       [4],
       [2],
       [2],
       [2],
       [2]])

In [ ]:
n1=np.array([1,3,3])
n2=np.array([1,2,5])
np.vstack((n2,n2))

array([[1, 2, 5],
       [1, 2, 5]])

In [ ]:
n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.sum([n1,n2])

21

In [ ]:
np.sum([n1,n2],axis=0)

array([5, 7, 9])

In [ ]:
np.sum([n1,n2],axis=1)

array([ 6, 15])

In [ ]:
n1=np.array([10,20,30,40,50,60])
n1


array([10, 20, 30, 40, 50, 60])

In [ ]:
np.mean(n1)
np.median(n1)
np.std(n1)

17.07825127659933

In [ ]:
np.mean(n1)

35.0

In [ ]:
np.median(n1)

35.0

In [ ]:
np.std(n1)

17.07825127659933

In [ ]:
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
n1[0]

array([1, 2, 3])

In [ ]:
n1[1]

array([4, 5, 6])

In [ ]:
n1[ : ,1]

array([2, 5, 8])

In [ ]:
n1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.transpose(n1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
n1=np.array([1,2,3,45,67,7,8,9])
np.save("mynumpy",n1)
n2=np.load("mynumpy.npy")
n2

array([ 1,  2,  3, 45, 67,  7,  8,  9])

In [ ]:
n1

array([ 1,  2,  3, 45, 67,  7,  8,  9])

In [26]:
n2


array([[1, 2, 3, 3],
       [2, 3, 4, 5]])

In [ ]:
n2

array([ 1,  2,  3, 45, 67,  7,  8,  9])

In [ ]:
n1=np.array([1,2,3,45,67,7,8,9])
np.save("mynumpy",n1)
np.load("mynumpy.npy")

array([ 1,  2,  3, 45, 67,  7,  8,  9])

In [ ]:
np.load("mynumpy.npy")ddd


SyntaxError: invalid syntax (2317453955.py, line 1)

In [ ]:
import numpy as np
n1=np.zeros((1,2))

n1


In [ ]:
n1

array([[0., 0.]])

In [ ]:
import numpy as np


In [ ]:
animal=np.array([1,2,34,4,1])

In [ ]:
animal

array([ 1,  2, 34,  4,  1])

In [ ]:
animal=np.array([[1,2,34,4,1],[2,1,]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
animal=np.array([[1,2,34,4,1],[2,1,2,]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
animal=np.array([[1,2,34,4,1],[2,1,1,2]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
animal=np.array([[1,2,34,4,1],[2,1,2,1,2]])

In [ ]:
animal

array([[ 1,  2, 34,  4,  1],
       [ 2,  1,  2,  1,  2]])

In [ ]:
type(animal)

numpy.ndarray

In [ ]:
n1=np.zeros(2,3)

TypeError: Cannot interpret '3' as a data type

In [ ]:
n1=np.zeros((2,3))

In [ ]:
n1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
n1=np.zeros((23,31))

In [ ]:
n1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0

In [ ]:
n1.shape

(23, 31)

In [ ]:
n1

array([[7, 7],
       [7, 7]])

In [ ]:
n2=np.arange(9,17)

In [ ]:
n2

array([ 9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
n2=np.arange(9,17,7)

In [ ]:
n2

array([ 9, 16])

In [ ]:
n1=np.arange(9,100,8)

In [ ]:
n1

array([ 9, 17, 25, 33, 41, 49, 57, 65, 73, 81, 89, 97])

In [ ]:
n1=np.random.randint(1,100)

In [ ]:
n1

64

In [ ]:
n1=np.random.randint(1,100,6)

In [ ]:
n1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0

In [ ]:
n1.shape

(23, 31)

In [ ]:
n1=np.array([1,2,3,5,2,1])

NameError: name 'np' is not defined

In [ ]:
import numpy as np
n1=np.array([1,2,3,5,2,1])

In [ ]:
n1

array([1, 2, 3, 5, 2, 1])

In [ ]:
n1.shape

(6,)

In [ ]:
n1=np.array([[1,2,3,5,2,1],[2,2,2,2,2,1]])

# 

In [ ]:
n1

array([[1, 2, 3, 5, 2, 1],
       [2, 2, 2, 2, 2, 1]])

In [ ]:
n1.shape

(2, 6)

In [ ]:
n1=np.random.randint(1,100)

In [ ]:
n1

22

In [ ]:
type(n1)

int

In [ ]:
n1.shape

AttributeError: 'int' object has no attribute 'shape'

In [ ]:
n1=np.random.randint(1,100,12)

In [ ]:
n1

array([85,  7, 98, 63, 30, 96, 54, 44, 92, 80, 49, 25])

In [ ]:
type(n1)

numpy.ndarray

In [ ]:
n1.shape

(12,)

In [ ]:
n1.shape=(2,3)

ValueError: cannot reshape array of size 12 into shape (2,3)

In [ ]:
n3=np.array([[1,2,3,4,1],[2,3,2,3,2]])

In [ ]:
n3

array([[1, 2, 3, 4, 1],
       [2, 3, 2, 3, 2]])

In [ ]:
type(n3)

numpy.ndarray

In [ ]:
n3.shape

(2, 5)

In [ ]:
n3.shape=(5,2)

In [ ]:
n3

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 2],
       [3, 2]])

In [ ]:
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(n1)

numpy.ndarray

In [ ]:
n1[0]

array([1, 2, 3])

In [ ]:
n1[2]

array([7, 8, 9])

In [ ]:
n1[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
n1[1]

array([4, 5, 6])

In [ ]:
n1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
n1[ :1]

array([[1, 2, 3]])

In [ ]:
n1[ :2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
n1[ : ,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [ ]:
n1[ : ,2]

array([3, 6, 9])

In [ ]:
n1=np.array([1,2,3,45,6,1])
n1

array([ 1,  2,  3, 45,  6,  1])

In [ ]:
np.save("animal",n1)

In [ ]:
np.load("animal.npy")

array([ 1,  2,  3, 45,  6,  1])