In [1]:
import scipy

In [3]:
print(scipy.constants.golden)

1.618033988749895


In [4]:
import numpy as np
from scipy import linalg

In [5]:
a=np.array([[1,2,-3],[2,-5,4],[5,4,-1]])
a

array([[ 1,  2, -3],
       [ 2, -5,  4],
       [ 5,  4, -1]])

In [6]:
b=np.array([[-3],[13],[5]])

In [7]:
b

array([[-3],
       [13],
       [ 5]])

In [8]:
x=linalg.solve(a,b)

In [9]:
x

array([[ 2.],
       [-1.],
       [ 1.]])

In [10]:
print(x)

[[ 2.]
 [-1.]
 [ 1.]]
